version: '3'
services:
  server:
    restart: always
    build: ./HomeHospital-Backend
    container_name: node-server
    ports:
      - 4000:4000
  frontend:
    restart: always
    build: ./HomeHospital-Frontend/hh-front/
    container_name: react-app
    # To run on the deployment server set ports to => 80:3000
    # To run on local machine for deveplopment set ports to => 3000:3000
    ports:
      - 3000:3000
